title: A Brief History of AI
description: Interactive exploration of AI's evolution from 1956 to present
baseurl: "/abriefhistoryofai"
url: "https://crankingai.github.io"

# Social/SEO
author: CrankingAI
twitter:
  username: crankingai
  card: summary

# GitHub Pages specific settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge